### ISSUE TITLE
pmfow crashing if no command is specified

### ISSUE THREAD

**Issue by Barrer898** [MasterJayanX/pmfow#2]
first time using pmfow, if you dont specify an command eg. list, update
it crashes immediately without any informaton how to use pmfow
![pmfow](https://github.com/MasterJayanX/pmfow/assets/102591557/cf6e4d1b-008b-4f0f-bc88-4cbc9c0f85cc)

**Comment by MasterJayanX** [comment]
Thanks for notifying me. The issue should be fixed in the next release. For now, use pmfow help to know how to use it (you can also refer to the Usage section in the README for more information on how to use it).

**Comment by MasterJayanX** [comment]
> Thanks for notifying me. The issue should be fixed in the next release. For now, use pmfow help to know how to use it (you can also refer to the Usage section in the README for more information on how to use it).

It's fixed now.
