### ISSUE TITLE
pmfow 0.1.5 missing dll while 0.1.4.1 works

### ISSUE THREAD

**Issue by Barrer898** [MasterJayanX/pmfow#3]
![pmfowbug](https://github.com/MasterJayanX/pmfow/assets/102591557/85100c69-06fb-40cf-9b49-332227a9f954)
i've noticed that pmfow 0.1.5 has missing dll errors while the older version 0.1.4.1 works without any errors.

**Comment by MasterJayanX** [comment]
I'm assuming that you're using the 64 bit version because the 32 bit works just fine. I will add the missing .dll file for the 64 bit binaries.

**Comment by MasterJayanX** [comment]
Done. You can also download the .dll file from the 64 bit folder.
